name: LastLevel stock checker

on:
  schedule:
    - cron: '*/3 * * * *'     # cada 3 min
  workflow_dispatch:          # botón Run workflow

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore state.json
        uses: actions/cache@v4
        with:
          path: state.json
          key: stock-state

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          N8N_WEBHOOK: ${{ secrets.N8N_WEBHOOK }}
        run: python stock_bot.py
